### PR TITLE
API 14 Compatibility Release

### PR DESCRIPTION
**Pull request by coding-red-panda**
## Description ##
I've increased the API version to 14 and loaded all the individiual Addons ingame.
I did not receive any errors on an initial play session, and things seem to be working as they should.

### CODE REVIEW

**Comment by nmsmith22389** [comment]
I haven't been paying much attention to this repo. Did you want me to merge this request?

**Comment by coding-red-panda** [comment]
Yes please!
I'm trying to make the Addon work properly under the current game, so there's probably a few more PR's coming based on feedback I collect.

Would also be cool if we could hook it up to curse so new versions can be pushed out

**Comment by nmsmith22389** [comment]
Ok I merged it. I also invited you as a collaborator so you should have push access as well. I think there is someone also managing the CandyBars addon and idk if it has its own repository or this one so maybe ask him and see if he wants to just make his own repository or also be a collaborator idk. I think his name should be on the curse page for it but I suppose with git you can just go back so he wont technically lose anything so it might just be ok. I'll just leave it up to you.

Thanks for working on this!

**Comment by coding-red-panda** [comment]
I'm also the one doing the candybars thing :D
I'm Tenpi on Curse

**Comment by nmsmith22389** [comment]
Cool! Also just saw all of your PRs! You are really going at it! 👍

**Pull request merged**
